layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: commits
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
    linkedin: noah-mancino
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
    twitter: noahdmancino
  # unsplash: your_username
  # vk: your_username
  # website: https://twitter.com
  # youtube: your_username

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/linux/linux.png
    
  - name: Deep Learning
    web_url: https://github.com/topics/deep-learning
    image_url: https://upload.wikimedia.org/wikipedia/commons/6/68/Gradient_ascent_%28surface%29.png
